---
version: "2"
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
  - "**/.*"
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/*.md"
  - "**/*.txt"
  - "go.mod"
  - "go.sum"
  - "LICENSE"
