---
dir: "internal/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName | lower}}_mock.go"

quiet: true
disable-version-string: true
boilerplate-file: "internal/mocks/boilerplate.go.txt"

packages:
  fillmore-labs.com/microbatch/internal/mocks:
    interfaces:
      BatchProcessor:
      NewTimer:
      Processor:
  fillmore-labs.com/microbatch/internal/timer:
    interfaces:
      Timer:
